.pragma library

const Character = [
    {"name": "骑士", "ename": "Knight", "id":  0, "skillNum": 3, "skinNum": 10},
    {"name": "游侠", "ename": "Ranger","id":  1, "skillNum": 0, "skinNum": 0},
    {"name": "法师", "ename": "Mage","id":  2, "skillNum": 0, "skinNum": 0},
    {"name": "刺客", "ename": "Assassin","id":  3, "skillNum": 0, "skinNum": 0},
    {"name": "炼金术士", "ename": "Alchemist","id":  4, "skillNum": 0, "skinNum": 0},
    {"name": "工程师", "ename": "Engineer","id":  5, "skillNum": 0, "skinNum": 0},
    {"name": "吸血鬼", "ename": "Vampire","id":  6, "skillNum": 0, "skinNum": 0},
    {"name": "圣骑士", "ename": "Paladin","id":  7, "skillNum": 0, "skinNum": 0},
    {"name": "精灵", "ename": "Elves","id":  8, "skillNum": 0, "skinNum": 0},
    {"name": "狼人", "ename": "Werewolf","id":  9, "skillNum": 0, "skinNum": 0},
    {"name": "牧师", "ename": "Priest","id":  10, "skillNum": 0, "skinNum": 0},
    {"name": "德鲁伊", "ename": "Druid","id":  11, "skillNum": 0, "skinNum": 0},
    {"name": "机器人", "ename": "Robot","id":  12, "skillNum": 0, "skinNum": 0},
    {"name": "狂战士", "ename": "Viking","id":  13, "skillNum": 0, "skinNum": 0},
    {"name": "死灵法师", "ename": "Necromancer","id":  14, "skillNum": 0, "skinNum": 0},
    {"name": "警官", "ename": "Officer","id":  15, "skillNum": 0, "skinNum": 0},
    {"name": "道士", "ename": "Taoist","id":  16, "skillNum": 0, "skinNum": 0},
    {"name": "超界者", "ename": "Transcendent","id":  17, "skillNum": 0, "skinNum": 0},
    {"name": "古代元素使", "ename": "Envoy","id":  18, "skillNum": 0, "skinNum": 0},
    {"name": "枭首者", "ename": "Beheaded","id":  19, "skillNum": 0, "skinNum": 0},
    {"name": "超时空忍者", "ename": "Ninja","id":  20, "skillNum": 0, "skinNum": 0},
    {"name": "特种骑士部队", "ename": "SpecialForces","id":  21, "skillNum": 0, "skinNum": 0},
    {"name": "气宗", "ename": "Airbender","id":  22, "skillNum": 0, "skinNum": 0},
    {"name": "恶魔术士", "ename": "Warlock","id":  23, "skillNum": 0, "skinNum": 0},
    {"name": "矿工", "ename": "Miner","id":  24, "skillNum": 0, "skinNum": 0},
    {"name": "陷阱大师", "ename": "TrapMaster","id":  25, "skillNum": 0, "skinNum": 0},
    {"name": "皮套王子", "ename": "CostumePrince","id":  26, "skillNum": 0, "skinNum": 0},
    {"name": "博士", "ename": "Doctor","id":  27, "skillNum": 0, "skinNum": 0},
    {"name": "剑宗", "ename": "SwordMaster","id":  28, "skillNum": 0, "skinNum": 0},
    {"name": "枪客", "ename": "Lancer","id":  29, "skillNum": 0, "skinNum": 0},
    {"name": "领主", "ename": "Warliege","id":  30, "skillNum": 0, "skinNum": 0},
    {"name": "咒法骑士", "ename": "ArcaneKnight","id":  31, "skillNum": 0, "skinNum": 0},
    {"name": "占星师", "ename": "Astrologist","id":  32, "skillNum": 0, "skinNum": 0},
    {"name": "武斗家", "ename": "Fighter","id":  33, "skillNum": 0, "skinNum": 0},
    {"name": "戏法师", "ename": "Joker","id":  34, "skillNum": 0, "skinNum": 0},
    {"name": "吟游诗人", "ename": "Bard","id":  35, "skillNum": 0, "skinNum": 0},
    {"name": "枪手", "ename": "Shooter","id":  36, "skillNum": 0, "skinNum": 0},
    {"name": "机械姬", "ename": "AiGirl","id":  37, "skillNum": 0, "skinNum": 0},
    {"name": "船长", "ename": "Captain","id":  38, "skillNum": 0, "skinNum": 0},
    {"name": "阴阳家", "ename": "YinYang","id":  39, "skillNum": 0, "skinNum": 0},
    {"name": "枪械专家", "ename": "GunsExpert","id":  40, "skillNum": 0, "skinNum": 0},
]

const Skill = [
    ["全力攻击", "混沌打击"],
    ["居合斩", "地堂刀"],
    ["寒冰刺穿", "火焰飓风"],
    ["分身术", "影遁"],
    ["元素药剂", "蜜汁饮剂"],
    ["机甲武装", "迎击炮台"],
    ["异界漩涡", "不朽之躯"],
    ["神化", "爆裂飞盾"],
    ["箭雨", "守护精灵"],
    ["嗜血斩击", "吞噬"],
    ["祈祷", "月影之息"],
    ["剧毒藤蔓", "召唤巨熊"],
    ["无人机集群", "电磁脉冲"],
    ["散打", "跳跃"],
    ["灾祸之石", "亡灵复生"],
    ["赏金标记", "空中支援"],
    ["乾坤大挪移", "御剑术"],
    [],
    [],
    [],
    [],
    [],
    ["斗转星移", "六脉神剑"],
    ["协力:艾利欧格", "阿蒙的庇护"],
    ["矿车速递", "沙虫来袭"],
    ["大变活人", "帽子戏法"],
    ["进击!水晶王蟹!", "降临!紫爵士!"],
    ["高能电球"],
    ["流云飞剑", "瞬步剑诀"],
    ["龙枪圣临", "陷阵枪诀"],
    ["决心猛冲", "黑暗领主"],
    ["庇护法阵"],
    ["命运之轮"],
    ["旋风腿"],
    ["幻幕戏法"],
    ["共振乐章"],
    ["狩猎领域"],
    [],
    [],
    [],
    [],
]

const Skin = [
    [
        {"name": "精英骑士", "init": 2000},
        {"name": "熔岩骑士", "init": -2},
        {"name": "哈士骑", "init": 5000},
        {"name": "爆米花", "init": -3},
        {"name": "聚变核心", "init": 12000},
        {"name": "电子骑士", "init": 0},
        {"name": "熊猫", "init": -1},
        {"name": "暗黑大骑士皮肤", "init": 0},
        {"name": "饕餮", "init": 10000},
        {"name": "国王", "init": 8000},
        {"name": "张飞", "init": 15000},
        {"name": "司锋团执事", "init": -8},
        {"name": "裁决", "init": 8000},
        {"name": "首席百夫长", "init": 0},
        {"name": "圣骑士我们走!", "init": 0},
        {"name": "赤焱", "init": 233},
        {"name": "号鸟婴鸟武鸟", "init": 9999},
        {"name": "二郎真君", "init": 9999},
        {"name": "《骑 土》", "init": -13},
        {"name": "苍蝇座", "init": -5},
        {"name": "元气奇事-草丛骑士", "init": -6},
        {"name": "元气奇事-亚伦", "init": 0},
        {"name": "《骑》", "init": -13},
        {"name": "黄忠 字汉升", "init": 12000},
        {"name": "元澜", "init": -6},
        {"name": "肉鸽", "init": -1},
        {"name": "雪山大猿王 皮肤", "init": 10000},
        {"name": "骑蛋", "init": -13},
        {"name": "狱火审判 杰洛特", "init": 0},
        {"name": "炽翼圣尊·傲天", "init": -19},
        {"name": "卡皮骑士巴拉", "init": -13},
        {"name": "电玩社·阿眠", "init": 0},
        {"name": "醒狮破晓·云霄", "init": -20},
        {"name": "破旧的手枪", "init": -13},
    ],
    [
        {"name": "幽灵", "init": 2000},
        {"name": "松鼠党", "init": 5000},
        {"name": "鲁道夫", "init": 5000},
        {"name": "啾啾", "init": 0},
        {"name": "夜莺", "init": 0},
        {"name": "神秘商贩 皮肤", "init": -5},
        {"name": "应龙", "init": 0},
        {"name": "立体主义", "init": 0},
        {"name": "老鼠国王", "init": 8000},
        {"name": "变脸", "init": 0},
        {"name": "以太枢机", "init": -8},
        {"name": "老伙计", "init": -5},
        {"name": "汉谟拉比王", "init": 0},
        {"name": "霓光", "init": -1},
        {"name": "猎鹰", "init": -10},
        {"name": "玉龙三太子", "init": 0},
        {"name": "《油 侠》", "init": -13},
        {"name": "喔喔", "init": -1},
        {"name": "双子座", "init": 0},
        {"name": "元气奇事-夜莺", "init": -16},
        {"name": "《侠》", "init": -13},
        {"name": "刘备 字玄德", "init": 0},
        {"name": "夜游神 皮肤", "init": 0},
        {"name": "猎魔男爵·克雷顿", "init": 0},
        {"name": "Oii喵", "init": -13},
        {"name": "侠蛋", "init": -13},
        {"name": "骑士·艾雷因", "init": -6},
        {"name": "卡皮游侠巴拉", "init": -6},
        {"name": "双锋夜影·西尔文", "init": 10000},
        {"name": "神之使者赫尔墨斯", "init": 0},
        {"name": "小明小红", "init": -13},
    ],
    [
        {"name": "黑暗萝莉", "init": 2000},
        {"name": "图书管理员", "init": 5000},
        {"name": "见习法师", "init": 2000},
        {"name": "女巫", "init": 2000},
        {"name": "春节", "init": 0},
        {"name": "拘魂者", "init": 0},
        {"name": "大巫师 皮肤", "init": -5},
        {"name": "夜", "init": 8000},
        {"name": "九尾狐", "init": 0},
        {"name": "小红帽", "init": 8000},
        {"name": "穆桂英", "init": -4},
        {"name": "神圣以太教皇", "init": -8},
        {"name": "贵族技师", "init": 10000},
        {"name": "御神子", "init": 0},
        {"name": "幻纶", "init": 0},
        {"name": "《发 师》", "init": -13},
        {"name": "孔雀公主", "init": 0},
        {"name": "琉璃珊", "init": -6},
        {"name": "天鹅座", "init": 0},
        {"name": "元气奇事-宝箱法师", "init": 0},
        {"name": "《法》", "init": -13},
        {"name": "迷雾女巫 皮肤", "init": 12000},
        {"name": "卞玲珑", "init": 0},
        {"name": "古灵精怪·幽铃", "init": 0},
        {"name": "法蛋", "init": -13},
        {"name": "卡皮法师巴拉", "init": -6},
        {"name": "学园偶像·歌穗", "init": 0},
        {"name": "俺的法师", "init": -6},
        {"name": "虚境幻灵·艾达", "init": -20},
        {"name": "焦土先知·巫娅", "init": 12000},
        {"name": "法典", "init": -13},
    ],
    [
        {"name": "死亡小分队", "init": 2000},
        {"name": "夜猫小分队", "init": 5000},
        {"name": "暗部", "init": 0},
        {"name": "黑帮兔", "init": 2000},
        {"name": "祭祀官", "init": 5000},
        {"name": "风林火山", "init": 0},
        {"name": "骷髅王 皮肤", "init": 0},
        {"name": "狰", "init": 0},
        {"name": "胡桃夹子", "init": 8000},
        {"name": "伍子胥", "init": 0},
        {"name": "银藏", "init": -8},
        {"name": "欺诈", "init": 0},
        {"name": "波斯王子", "init": 0},
        {"name": "南十字星", "init": 0},
        {"name": "ヾ(ﾟ∀ﾟ)ﾉ\"", "init": -4},
        {"name": "六耳猕猴", "init": -10},
        {"name": "《刺 克》", "init": -13},
        {"name": "琥珀川", "init": -6},
        {"name": "天蝎座", "init": 0},
        {"name": "吕布 字奉先", "init": 0},
        {"name": "元气奇事-风林火山", "init": -15},
        {"name": "《刺》", "init": -13},
        {"name": "深渊潜航者 皮肤", "init": -5},
        {"name": "刺蛋", "init": -13},
        {"name": "卡皮刺客巴拉", "init": -8},
        {"name": "海神波塞冬", "init": 0},
        {"name": "黯乐寅主·阿什尔", "init": -6},
        {"name": "血刃", "init": -13},
    ],
    [
        {"name": "唱片术士", "init": 2000},
        {"name": "圣诞老人 红", "init": 5000},
        {"name": "财神爷", "init": 0},
        {"name": "鸟嘴医生", "init": 8000},
        {"name": "瓦克恩头目 皮肤", "init": 0},
        {"name": "獓因", "init": 0},
        {"name": "刑罚", "init": -1},
        {"name": "包青天", "init": -5},
        {"name": "猛毒鱼人", "init": 8000},
        {"name": "阿兹台克祭祀长", "init": 0},
        {"name": "茉茉", "init": 12000},
        {"name": "琵琶仙", "init": 9999},
        {"name": "《炼 金 木 土》", "init": -13},
        {"name": "哭哭柠", "init": -5},
        {"name": "金牛座", "init": 12000},
        {"name": "左慈 字元放", "init": -12},
        {"name": "《金》", "init": -13},
        {"name": "巫婆", "init": 4000},
        {"name": "实验员·叶梨", "init": 0},
        {"name": "金蛋", "init": -13},
        {"name": "卡皮炼金术师巴拉", "init": -13},
        {"name": "元素学者·莉兹", "init": 12000},
        {"name": "赤涛残火·霍克", "init": 12000},
        {"name": "休眠的毒泡泡泵", "init": -13},
    ],
    [
        {"name": "魔改后工程师", "init": 2000},
        {"name": "原型机", "init": 5000},
        {"name": "孔明灯", "init": 0},
        {"name": "温泉蛋", "init": 2000},
        {"name": "投币式乐队机器人#1", "init": 5000},
        {"name": "世界你好", "init": 0},
        {"name": "镭射幽浮 皮肤", "init": 0},
        {"name": "皇天", "init": -5},
        {"name": "驱邪", "init": 6000},
        {"name": "项羽", "init": 15000},
        {"name": "行为怪诞的小丑", "init": 0},
        {"name": "罐装大王", "init": 0},
        {"name": "古祖铸铜者", "init": 0},
        {"name": "伪装战甲", "init": 0},
        {"name": "欧博士", "init": -8},
        {"name": "《工 呈 师》", "init": -13},
        {"name": "紫金红葫芦", "init": -10},
        {"name": "水瓶座", "init": 12000},
        {"name": "华佗 字元化", "init": 0},
        {"name": "《程》", "init": -13},
        {"name": "凹凸蓝", "init": -12},
        {"name": "程蛋", "init": -13},
        {"name": "发明社·亨利", "init": 12000},
        {"name": "卡皮工程师巴拉", "init": -13},
        {"name": "嗒啦啦和伙伴们", "init": -8},
        {"name": "程序猿", "init": -19},
        {"name": "孤械永契·余烬", "init": 0},
        {"name": "欠欠时代冲锋枪", "init": -13},
    ],
    [
        {"name": "血伯爵", "init": 2000},
        {"name": "警长", "init": 0},
        {"name": "真 吸血鬼", "init": 2000},
        {"name": "杰克南瓜", "init": 2000},
        {"name": "白无常", "init": 5000},
        {"name": "银爵", "init": 0},
        {"name": "幽灵王 皮肤", "init": -5},
        {"name": "梼杌", "init": 0},
        {"name": "范无救与谢必安", "init": 0},
        {"name": "湮灭", "init": 0},
        {"name": "夜魔女莉莉丝", "init": 15000},
        {"name": "猩红", "init": -10},
        {"name": "晶晶", "init": 0},
        {"name": "《口及 血 鬼》", "init": -13},
        {"name": "乌鸦座", "init": -10},
        {"name": "司马懿 字仲达", "init": 0},
        {"name": "《鬼》", "init": -13},
        {"name": "商尊", "init": -6},
        {"name": "学生会长·桃子", "init": 18000},
        {"name": "鬼蛋", "init": -13},
        {"name": "红影裁决·维恩", "init": 0},
        {"name": "卡皮吸血鬼巴拉", "init": -13},
        {"name": "蜘蛛胡椒", "init": -13},
        {"name": "俺的吸血鬼", "init": -6},
        {"name": "鲜血酒杯", "init": -13},
    ],
    [
        {"name": "魔龙骑士", "init": 2000},
        {"name": "工业化", "init": 0},
        {"name": "圣诞老人 绿", "init": 5000},
        {"name": "增长天王", "init": 0},
        {"name": "守护骑士", "init": -3},
        {"name": "银翼骑士团", "init": -4},
        {"name": "大骑士 皮肤", "init": -5},
        {"name": "苦", "init": -4},
        {"name": "帝江", "init": 0},
        {"name": "关羽", "init": 0},
        {"name": "司锋团之鞭", "init": -8},
        {"name": "人鱼统领", "init": -5},
        {"name": "锈蚀战甲", "init": 0},
        {"name": "斯巴达战士", "init": 0},
        {"name": "白钢", "init": 12000},
        {"name": "猪悟能", "init": 9999},
        {"name": "《圣 骑 土》", "init": -13},
        {"name": "湍流枫", "init": -6},
        {"name": "盾牌座", "init": 0},
        {"name": "《圣》", "init": -13},
        {"name": "许诸 字仲康", "init": 12000},
        {"name": "西西红柿", "init": -13},
        {"name": "圣蛋", "init": -13},
        {"name": "地狱之斧·格雷戈", "init": 18000},
        {"name": "卡皮圣骑士巴拉", "init": -13},
        {"name": "海焰战姬·希格", "init": 0},
        {"name": "俺的圣骑士", "init": -6},
        {"name": "神圣连枷", "init": -13},
        {"name": "太阳神阿波罗", "init": 0},
    ],
    [
        {"name": "恢复", "init": 2000},
        {"name": "冰雪女王", "init": 0},
        {"name": "嫦娥", "init": 0},
        {"name": "嗒啦啦", "init": -13},
        {"name": "巡林者", "init": 0},
        {"name": "曼陀罗魔花 皮肤", "init": -5},
        {"name": "毕方", "init": 0},
        {"name": "糖梅仙子", "init": 0},
        {"name": "黄忠", "init": -5},
        {"name": "人鱼公主", "init": 0},
        {"name": "奥林匹斯山的月光", "init": -4},
        {"name": "闪回", "init": 0},
        {"name": "杏仙", "init": -10},
        {"name": "《晶 灵》", "init": -13},
        {"name": "射手座", "init": 0},
        {"name": "《精》", "init": -13},
        {"name": "星奈", "init": -6},
        {"name": "步练师", "init": 0},
        {"name": "体育生·柚希", "init": 0},
        {"name": "精蛋", "init": -13},
        {"name": "云裳灵羽·琉璃", "init": 0},
        {"name": "卡皮精灵巴拉", "init": -6},
        {"name": "月神阿尔忒弥斯", "init": 0},
        {"name": "潮音猎手·芷汐", "init": 12000},
        {"name": "俺的精灵", "init": -6},
        {"name": "古老的弓", "init": -13},
    ],
    [
        {"name": "钢铁战狼", "init": 2000},
        {"name": "熊孩子", "init": 0},
        {"name": "齐天大圣", "init": 2000},
        {"name": "海公公", "init": 2000},
        {"name": "小虎队", "init": 0},
        {"name": "彩蛋", "init": 2000},
        {"name": "美洲豹", "init": 0},
        {"name": "火焰地狱契约", "init": 0},
        {"name": "水晶巨蟹 皮肤", "init": -5},
        {"name": "穷奇", "init": 12000},
        {"name": "豆娃", "init": -3},
        {"name": "和蔼的外婆", "init": 8000},
        {"name": "哪吒", "init": 0},
        {"name": "天狼", "init": 0},
        {"name": "北风熊灵", "init": 15000},
        {"name": "惊骇", "init": 0},
        {"name": "大力牛魔王", "init": 0},
        {"name": "《狼 入》", "init": -13},
        {"name": "巨蟹座", "init": -10},
        {"name": "张飞 字益德", "init": -10},
        {"name": "《狼》", "init": -13},
        {"name": "螂人", "init": -19},
        {"name": "肌肉驯鹿", "init": -8},
        {"name": "漆夜猎手·格雷森", "init": 12000},
        {"name": "狼蛋", "init": -13},
        {"name": "卡皮狼人巴拉", "init": -6},
        {"name": "失去伪装的面具熊", "init": 10000},
        {"name": "蚀月魔狼 皮肤", "init": -10},
        {"name": "高雅的企鹅", "init": 11999},
        {"name": "俺的狼人", "init": -6},
        {"name": "炽热爪刃", "init": -13},
        {"name": "霜银狼王·凛风", "init": 0},
    ],
    [
        {"name": "教会", "init": 5000},
        {"name": "红衣教主", "init": 2000},
        {"name": "兔兔", "init": 0},
        {"name": "天国巡音", "init": 18000},
        {"name": "阿努比斯 皮肤", "init": -5},
        {"name": "露", "init": 8000},
        {"name": "猼訑", "init": 0},
        {"name": "医师", "init": 6000},
        {"name": "漫游仙境", "init": 8000},
        {"name": "白蛇", "init": 0},
        {"name": "日蚀", "init": 10000},
        {"name": "飞天", "init": 15000},
        {"name": "爪爪", "init": -6},
        {"name": "圣洁", "init": 0},
        {"name": "转世金蝉", "init": -12},
        {"name": "《目 师》", "init": -13},
        {"name": "处女座", "init": 0},
        {"name": "《牧》", "init": -13},
        {"name": "蔡文姬", "init": 0},
        {"name": "辉洁星使·伊丽莎白", "init": 0},
        {"name": "牧蛋", "init": -13},
        {"name": "桂语·梦柔柔", "init": -6},
        {"name": "卡皮牧师巴拉", "init": -13},
        {"name": "校医室·云蓁", "init": 0},
        {"name": "爱神阿芙洛狄忒", "init": 0},
        {"name": "腐壤医者·鸦", "init": 12000},
        {"name": "俺的牧师", "init": -6},
        {"name": "木制十字架", "init": -13},
    ],
    [
        {"name": "先知", "init": 5000},
        {"name": "上班族", "init": 0},
        {"name": "驯鹿", "init": 5000},
        {"name": "龙王", "init": 0},
        {"name": "霜烬", "init": 0},
        {"name": "年兽 皮肤", "init": 0},
        {"name": "白泽", "init": 0},
        {"name": "诸葛亮", "init": 15000},
        {"name": "可怖的驯兽师", "init": 15000},
        {"name": "大发明家", "init": 0},
        {"name": "神鹿", "init": 0},
        {"name": "悖论", "init": 0},
        {"name": "我不是德鲁伊", "init": 0},
        {"name": "鹿力大仙", "init": -10},
        {"name": "《德鲁尹》", "init": -13},
        {"name": "魔蝎座", "init": 12000},
        {"name": "祝融姊姊", "init": 0},
        {"name": "《德》", "init": -13},
        {"name": "唐吟", "init": -6},
        {"name": "风纪·爱丽丝", "init": 0},
        {"name": "德蛋", "init": -13},
        {"name": "花蝶仙姬·洛芙蕾", "init": 0},
        {"name": "卡皮德鲁伊巴拉", "init": -6},
        {"name": "森灵秘使·古司", "init": 16000},
        {"name": "俺的德鲁伊", "init": -6},
        {"name": "牧神潘", "init": 0},
        {"name": "树妖王 皮肤", "init": 12000},
        {"name": "嘎嘣脆的骨头", "init": -13},
    ],
    [
        {"name": "荒野机甲", "init": 5000},
        {"name": "十以内加减法专用机器人", "init": -1},
        {"name": "末日科技实验体", "init": -4},
        {"name": "巨像 祖兰 皮肤", "init": 0},
        {"name": "9102", "init": -1},
        {"name": "女娲", "init": -5},
        {"name": "治疫", "init": 6000},
        {"name": "投币式乐队机器人#2", "init": -6},
        {"name": "虞机", "init": 15000},
        {"name": "咯咯作响的提线木偶", "init": 0},
        {"name": "瓶中之灵", "init": 8000},
        {"name": "摩艾石像", "init": -5},
        {"name": "破坏炮", "init": -10},
        {"name": "奔波儿灞", "init": 12000},
        {"name": "《鸡 器 人》", "init": -13},
        {"name": "望远镜座", "init": 12000},
        {"name": "元气奇事-自爆机器人", "init": -6},
        {"name": "《器》", "init": -13},
        {"name": "庞统 字士元", "init": 12000},
        {"name": "机蛋", "init": -13},
        {"name": "最强学生·奇宇", "init": 12000},
        {"name": "卡皮机器人巴拉", "init": -13},
        {"name": "缄默的半成品·X", "init": 12000},
        {"name": "卫星浮游炮", "init": -13},
    ],
    [
        {"name": "摔跤大师", "init": 0},
        {"name": "狂乱的制裁之拳", "init": -4},
        {"name": "丧尸", "init": 0},
        {"name": "无头骑士 皮肤", "init": -5},
        {"name": "龙的传人", "init": 0},
        {"name": "思", "init": -5},
        {"name": "䑏疏", "init": 12000},
        {"name": "公正", "init": -6},
        {"name": "权虎鹰", "init": -1},
        {"name": "皇帝的新衣", "init": 0},
        {"name": "武松", "init": 0},
        {"name": "海马斗士", "init": 10000},
        {"name": "钢铁焚化者", "init": 0},
        {"name": "维京王", "init": 15000},
        {"name": "雷暴", "init": -6},
        {"name": "利爪", "init": 0},
        {"name": "《狂 战 土》", "init": -13},
        {"name": "金翅大鹏雕", "init": 0},
        {"name": "岩祖 皮肤", "init": -5},
        {"name": "狮子座", "init": 0},
        {"name": "《狂》", "init": -13},
        {"name": "关羽 字云长", "init": 0},
        {"name": "逐日者·乔尼", "init": 15000},
        {"name": "狂蛋", "init": -13},
        {"name": "卡皮狂战士巴拉", "init": -6},
        {"name": "冲浪社·凌涛", "init": 0},
        {"name": "勇士阿喀琉斯", "init": 12000},
        {"name": "俺的狂战士", "init": -6},
        {"name": "拳套", "init": -13},
        {"name": "鹿鸣金胄·钧天", "init": 123456789},
    ],
    [
        {"name": "彩蛋兔皮肤", "init": -5},
        {"name": "狂热信徒", "init": -7},
        {"name": "特技车手", "init": 10000},
        {"name": "陆吾", "init": 0},
        {"name": "青蛇", "init": 0},
        {"name": "新月", "init": -5},
        {"name": "猫神芭丝特", "init": 15000},
        {"name": "极光", "init": -6},
        {"name": "冷月", "init": 0},
        {"name": "波丝", "init": -10},
        {"name": "《死 灵 发 师》", "init": -13},
        {"name": "仙后座", "init": 0},
        {"name": "小幽", "init": -8},
        {"name": "貂蝉", "init": 0},
        {"name": "《灵》", "init": -13},
        {"name": "咲莉", "init": -6},
        {"name": "手机党小梦", "init": 0},
        {"name": "灵蛋", "init": -13},
        {"name": "卡皮死灵法师巴拉", "init": -6},
        {"name": "奇迹乐章·奏", "init": 0},
        {"name": "橘焰魔眼·薇拉", "init": 12000},
        {"name": "俺的死灵法师", "init": -6},
        {"name": "珠澜贝主·铂尔", "init": 0},
        {"name": "瘟疫之杖", "init": -13},
    ],
    [
        {"name": "4亿探长", "init": 8000},
        {"name": "锦衣卫", "init": 0},
        {"name": "吸血鬼猎人", "init": 12000},
        {"name": "钟馗", "init": 123456789},
        {"name": "金面猴王 皮肤", "init": -5},
        {"name": "幽灵船长", "init": 0},
        {"name": "贵族警督", "init": 10000},
        {"name": "法老王", "init": 15000},
        {"name": "法槌", "init": 12000},
        {"name": "《警 关》", "init": -13},
        {"name": "托塔天王", "init": 9999},
        {"name": "羊马它", "init": -6},
        {"name": "天秤座", "init": -10},
        {"name": "马超 字孟起", "init": -10},
        {"name": "《警》", "init": -13},
        {"name": "凹凸红", "init": -10},
        {"name": "赤色暴君·里昂", "init": 0},
        {"name": "警蛋", "init": -13},
        {"name": "卡皮警官巴拉", "init": -6},
        {"name": "狱海提督·迪伦", "init": 0},
        {"name": "棒球社·道奇", "init": 12000},
        {"name": "罪恶克星", "init": -13},
    ],
    [
        {"name": "律法", "init": -6},
        {"name": "驱魔道人", "init": 8000},
        {"name": "天君", "init": 0},
        {"name": "太上老君", "init": 0},
        {"name": "哥布林祭师 皮肤", "init": -5},
        {"name": "鬼鬼祟祟的魔术师", "init": -5},
        {"name": "雷霆", "init": 0},
        {"name": "蒸汽符师", "init": 10000},
        {"name": "描仙郎", "init": 0},
        {"name": "汐羽", "init": 0},
        {"name": "昊天金阙无上至尊自然妙有弥罗至真玉皇上帝", "init": 0},
        {"name": "《道 土》", "init": -13},
        {"name": "双鱼座", "init": -10},
        {"name": "波子", "init": -8},
        {"name": "《道》", "init": -13},
        {"name": "陆逊 字伯言", "init": 0},
        {"name": "不是，哥们", "init": -4},
        {"name": "学霸·思辰", "init": 10000},
        {"name": "道蛋", "init": -13},
        {"name": "教主·浮士德", "init": 0},
        {"name": "卡皮道士巴拉", "init": -6},
        {"name": "尖齿主厨·布鲁斯", "init": 16000},
        {"name": "道剑", "init": -13},
    ],
    [
        {"name": "冥王哈迪斯", "init": 0},
        {"name": "超蛋", "init": -13},
        {"name": "卡皮超界者巴拉", "init": -6},
    ],
    [
        {"name": "千梦沉渊·黛澜", "init": 0},
        {"name": "元蛋", "init": -13},
    ],
    [
    ],
    [
        {"name": "青空之翼·鸢", "init": 0},
        {"name": "忍蛋", "init": -13},
        {"name": "卡皮超时空忍者巴拉", "init": -6},
        {"name": "沙海魅影·莎夜", "init": 0},
    ],
    [
    ],
    [
        {"name": "魔道巨擘", "init": 0},
        {"name": "阿箔", "init": -10},
        {"name": "空", "init": 0},
        {"name": "《汽 宗》", "init": -13},
        {"name": "罗盘座", "init": -10},
        {"name": "《气》", "init": -13},
        {"name": "机械皇帝 皮肤", "init": 12000},
        {"name": "夏侯惇 字元让", "init": 16000},
        {"name": "气蛋", "init": -13},
        {"name": "武术队·李云飞", "init": 15000},
        {"name": "苍风掠霄·岚枭", "init": 0},
        {"name": "卡皮气宗巴拉", "init": -6},
        {"name": "银霆破晓·艾瑟尔", "init": 12000},
        {"name": "天地通意拳", "init": -13},
    ],
    [
        {"name": "关于我转生为一个少女在 异世界修习恶魔法术这档事", "init": 0},
        {"name": "咬咬", "init": 12000},
        {"name": "被恶魔侵蚀的女孩", "init": 0},
        {"name": "《我 真 可 爱！》", "init": -13},
        {"name": "圣婴大王", "init": -10},
        {"name": "小熊座与大熊座", "init": 0},
        {"name": "《魔》", "init": -13},
        {"name": "小乔", "init": 0},
        {"name": "混沌魔王·暗月", "init": 0},
        {"name": "魔蛋", "init": -13},
        {"name": "卡皮恶魔术士巴拉", "init": -6},
        {"name": "园艺社·艾茵", "init": 15000},
        {"name": "浮游绮梦·玛丽娜", "init": 0},
        {"name": "俺的恶魔术士", "init": -6},
        {"name": "暗星之钥", "init": -13},
        {"name": "哀渡星河·银珠", "init": -6},
    ],
    [
        {"name": "玉兔", "init": 0},
        {"name": "《旷 工》", "init": -13},
        {"name": "兰琪琪", "init": -1},
        {"name": "鲸鱼座", "init": -10},
        {"name": "掘金骑手", "init": -1},
        {"name": "大乔", "init": 0},
        {"name": "《矿》", "init": -13},
        {"name": "蜜糖", "init": 0},
        {"name": "凹凸粉", "init": -10},
        {"name": "火山沙虫 皮肤", "init": 15000},
        {"name": "甜心公主·艾洁丽卡", "init": 18000},
        {"name": "矿蛋", "init": -13},
        {"name": "卡皮矿工巴拉", "init": -6},
        {"name": "夏憩·月绵绵", "init": -6},
        {"name": "骑行社·莉悠", "init": 0},
        {"name": "狂浪锚歌·浪芽", "init": 12000},
        {"name": "铁镐", "init": -13},
    ],
    [
        {"name": "阎魔王", "init": 9999},
        {"name": "《馅 阱 大 师》", "init": -13},
        {"name": "白羊座", "init": -10},
        {"name": "厚礼", "init": -5},
        {"name": "《陷》", "init": -13},
        {"name": "星算子", "init": 0},
        {"name": "孙权 字仲谋", "init": 18000},
        {"name": "陷蛋", "init": -13},
        {"name": "万灵戏法·杰克", "init": 15000},
        {"name": "卡皮陷阱大师巴拉", "init": -13},
        {"name": "生物社·池沼", "init": 16000},
        {"name": "俺的陷阱大师", "init": -6},
        {"name": "勾索枪", "init": -13},
    ],
    [
        {"name": "欧博士的火箭(低配版)", "init": 0},
        {"name": "苹果喵", "init": 9999},
        {"name": "沙和尚", "init": 12000},
        {"name": "《皮 套 王 孒》", "init": -13},
        {"name": "《皮》", "init": -13},
        {"name": "大家饿少女", "init": 0},
        {"name": "南瓜公爵", "init": -5},
        {"name": "蝘蜓座", "init": -10},
        {"name": "皮蛋", "init": -13},
        {"name": "国王·诺亚", "init": -6},
        {"name": "美术社·墨彩", "init": 12000},
        {"name": "卡皮皮套王子巴拉", "init": -6},
        {"name": "御魂行者·洛伊斯", "init": 0},
        {"name": "塑料粘液枪", "init": -13},
    ],
    [
        {"name": "高级指挥官", "init": 0},
        {"name": "《博 土》", "init": -13},
        {"name": "《博》", "init": -13},
        {"name": "罗刹姬", "init": 0},
        {"name": "甄姬", "init": 16000},
        {"name": "花舞", "init": -6},
        {"name": "博蛋", "init": -13},
        {"name": "蝠翼冥冠·卡蜜拉", "init": 15000},
        {"name": "卡皮博士巴拉", "init": -6},
        {"name": "智慧女神雅典娜", "init": 0},
    ],
    [
        {"name": "孙尚香", "init": 0},
        {"name": "《剑总》", "init": -13},
        {"name": "《剑》", "init": -13},
        {"name": "凛音", "init": -6},
        {"name": "青锋", "init": 0},
        {"name": "剑蛋", "init": -13},
        {"name": "绯蔷之主·伊芙琳", "init": 0},
        {"name": "卡皮剑宗巴拉", "init": -6},
        {"name": "罪恶佳人·罗娜", "init": 0},
        {"name": "俺的剑宗", "init": -6},
        {"name": "窃月", "init": -6},
    ],
    [
        {"name": "赵云 字子龙", "init": 0},
        {"name": "《仓 客》", "init": -13},
        {"name": "《枪》", "init": -13},
        {"name": "末力 皮肤", "init": -5},
        {"name": "骸星", "init": 0},
        {"name": "明霄", "init": -6},
        {"name": "枪蛋", "init": -13},
        {"name": "金刚猛男", "init": 9999},
        {"name": "卡皮枪客巴拉", "init": -6},
        {"name": "战神阿瑞斯", "init": 0},
        {"name": "俺的枪客", "init": -6},
        {"name": "裁星", "init": -6},
    ],
    [
        {"name": "曹操 字孟德", "init": 12000},
        {"name": "《令 主》", "init": -13},
        {"name": "《领》", "init": -13},
        {"name": "影月", "init": 0},
        {"name": "寅将军", "init": 0},
        {"name": "魔械统帅·奥古斯都", "init": 0},
        {"name": "领蛋", "init": -13},
        {"name": "摇滚社·佐克", "init": 0},
        {"name": "卡皮领主巴拉", "init": -6},
        {"name": "缚誓魔龙·枷顿", "init": 0},
        {"name": "俺的领主", "init": -6},
    ],
    [
        {"name": "周瑜 字公瑾", "init": 0},
        {"name": "《咒》", "init": -13},
        {"name": "凹凸黑", "init": -10},
        {"name": "铁扇公主", "init": 0},
        {"name": "咒蛋", "init": -13},
        {"name": "渡鸦之咒·枯木", "init": 16000},
        {"name": "卡皮咒法骑士巴拉", "init": -6},
        {"name": "侦探社·夏洛特", "init": 12000},
        {"name": "俺的咒法骑士", "init": -6},
    ],
    [
        {"name": "诸葛亮 字孔明", "init": 0},
        {"name": "《星》", "init": -13},
        {"name": "极光圣骑", "init": 0},
        {"name": "星蛋", "init": -13},
        {"name": "UFO研究员·朱利安", "init": 12000},
        {"name": "卡皮占星师巴拉", "init": -6},
        {"name": "渊触舵手·黑萨姆", "init": 12000},
        {"name": "瞳海星沉·天河", "init": 12000},
        {"name": "俺的占星师", "init": -6},
    ],
    [
        {"name": "关银屏", "init": 0},
        {"name": "《武》", "init": -13},
        {"name": "玉面狐狸", "init": 0},
        {"name": "晴雪·糖悠悠", "init": -6},
        {"name": "武蛋", "init": -13},
        {"name": "新闻社·知夏", "init": 0},
        {"name": "卡皮武斗家巴拉", "init": -6},
        {"name": "炎之魔使·伊格尼丝", "init": 0},
        {"name": "碧浪轻翼·青雀", "init": 0},
        {"name": "俺的武斗家", "init": -6},
    ],
    [
        {"name": "荒诞之梦", "init": -19},
        {"name": "《戏》", "init": -13},
        {"name": "戏蛋", "init": -13},
        {"name": "学园祭女仆·真优", "init": 16000},
        {"name": "影流宗师", "init": 9999},
        {"name": "卡皮戏法师巴拉", "init": -6},
        {"name": "绮光旋乐·聆妙", "init": -6},
        {"name": "俺的戏法师", "init": -6},
    ],
    [
        {"name": "猫语歌者·妮芙蒂", "init": 0},
        {"name": "《诗》", "init": -13},
        {"name": "诗蛋", "init": -13},
        {"name": "啦啦队·晴空", "init": 0},
        {"name": "卡皮吟游诗人巴拉", "init": -6},
        {"name": "秋色·枫恬恬", "init": -6},
        {"name": "炼狱弦使·烬歌", "init": 12000},
        {"name": "俺的吟游诗人", "init": -6},
    ],
    [
        {"name": "炽焰亡徒·卢西恩", "init": 0},
        {"name": "《手》", "init": -13},
        {"name": "手蛋", "init": -13},
        {"name": "卡皮枪手巴拉", "init": -6},
        {"name": "主教·赛奥菲尔", "init": -6},
        {"name": "射击社·星衡", "init": 16000},
    ],
    [
        {"name": "煌蜂", "init": 0},
        {"name": "沧海遗珠·蓝歌", "init": 0},
        {"name": "姬蛋", "init": -13},
        {"name": "卡皮机械姬巴拉", "init": -6},
        {"name": "皇后·卡伊莎", "init": -6},
        {"name": "荒原初芽·薇塔", "init": 16000},
        {"name": "俺的机械姬", "init": -6},
    ],
    [
        {"name": "幽冥船长·斯派克", "init": 0},
        {"name": "船蛋", "init": -13},
        {"name": "深海樊笼·编号001", "init": 10000},
        {"name": "卡皮船长巴拉", "init": -6},
        {"name": "潜水社·吉浪", "init": 12000},
    ],
    [
        {"name": "极域龙姬·寒烬", "init": 0},
        {"name": "阴阳蛋", "init": -13},
    ],
    [
        {"name": "秘灵契主·珀莉", "init": 0},
        {"name": "械蛋", "init": -13},
    ],
]


const Pet = [
    {"name": "阿凉", "id": 0},
    {"name": "旺财", "id": 1},
    {"name": "火腿", "id": 2},
    {"name": "蓝色史莱姆", "id": 3},
    {"name": "萝卜卜", "id": 4},
    {"name": "熊猫", "id": 5},
    {"name": "蹦蹦", "id": 6},
    {"name": "罐头猪", "id": 7},
    {"name": "嗒普", "id": 8},
    {"name": "豆娃", "id": 9},
    {"name": "鸽子", "id": 10},
    {"name": "扑扑", "id": 11},
    {"name": "海豹宝宝", "id": 12},
    {"name": "祖传漏洞", "id": 13},
    {"name": "来福", "id": 14},
    {"name": "粉红小河马", "id": 15},
    {"name": "小天狗", "id": 16},
    {"name": "", "id": 17},
    {"name": "阿巴", "id": 18},
    {"name": "黑麦", "id": 19},
    {"name": "冷喵", "id": 20},
    {"name": "雪诺", "id": 21},
    {"name": "趴趴", "id": 22},
    {"name": "牛仔", "id": 23},
    {"name": "阿凉长官", "id": 24},
    {"name": "布拉尼", "id": 25},
    {"name": "小兲", "id": 26},
    {"name": "夜歌", "id": 27},
    {"name": "太郎", "id": 28},
    {"name": "布丁", "id": 29},
    {"name": "泡泡", "id": 30},
    {"name": "波奇", "id": 31},
    {"name": "栗子", "id": 32},
    {"name": "焱焱", "id": 33},
    {"name": "胡椒", "id": 34},
    {"name": "迷迭猫", "id": 35},
    {"name": "九折", "id": 36},
    {"name": "冲鸭", "id": 37},
    {"name": "萨卡萨卡", "id": 38},
    {"name": "招财", "id": 39},
    {"name": "小锤锤", "id": 40},
    {"name": "粽小子", "id": 41},
    {"name": "胡椒导演", "id": 42},
    {"name": "进击的漏洞", "id": 43},
    {"name": "财满满", "id": 44},
    {"name": "火力喵", "id": 45},
    {"name": "小史莱姆", "id": 46},
    {"name": "粽大哥", "id": 47},
    {"name": "土嚎", "id": 48},
    {"name": "小豚豚", "id": 49},
    {"name": "珍珠防御塔", "id": 50},
    {"name": "小小教官", "id": 51},
    {"name": "火力雪人王", "id": 52},
    {"name": "凉块", "id": 53},
    {"name": "来财", "id": 54},
]